# Generated by Django 2.1.7 on 2019-03-20 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('contratacao', models.DateField(verbose_name='Data de contratação')),
                ('telefone1', models.CharField(max_length=20, verbose_name='Telefone')),
                ('telefone2', models.CharField(max_length=20, verbose_name='Telefone 2')),
                ('foto', models.FileField(upload_to='')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
