# Generated by Django 2.1.7 on 2019-03-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(upload_to='templates/statics/img/avatars'),
        ),
    ]
