# Generated by Django 2.1.7 on 2019-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_auto_20190320_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
