# Generated by Django 2.1.7 on 2019-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_auto_20190321_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(upload_to='avatars'),
        ),
    ]
