# Generated by Django 2.1.7 on 2019-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_auto_20190321_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
    ]
