# Generated by Django 2.1.7 on 2019-03-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_funcionario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
