# Generated by Django 2.1.7 on 2019-03-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_funcionario_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisioterapeuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crefito', models.CharField(max_length=50, verbose_name='CREFITO')),
                ('especializacao', models.TextField()),
            ],
            options={
                'verbose_name': 'Fisioterapeuta',
                'verbose_name_plural': 'Fisioterapeutas',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino'), ('nd', 'Não declarado')], max_length=2, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='fisioterapeuta',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario'),
        ),
    ]
