# Generated by Django 2.1.7 on 2019-03-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_auto_20190321_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
    ]
