# Generated by Django 2.1.7 on 2019-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_auto_20190321_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisioterapeuta',
            name='cursos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fisioterapeuta',
            name='especializacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
