# Generated by Django 2.1.7 on 2019-03-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_auto_20190321_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esteticista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario')),
            ],
            options={
                'verbose_name': 'Esteticista',
                'verbose_name_plural': 'Esteticistas',
            },
        ),
    ]
