# Generated by Django 2.1.7 on 2019-03-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0015_instrutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticista',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario'),
        ),
        migrations.AlterField(
            model_name='fisioterapeuta',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('União Estável', 'União Estável')], max_length=50, null=True, verbose_name='Estado civíl'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario'),
        ),
    ]
