# Generated by Django 2.1.7 on 2019-04-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0018_auto_20190329_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
