# Generated by Django 2.1.7 on 2019-04-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0022_auto_20190404_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='conselho',
            field=models.CharField(blank=True, choices=[('CREFITO', 'CREFITO'), ('CREF', 'CREF')], max_length=7, null=True, verbose_name='Conselho de Classe'),
        ),
    ]
