# Generated by Django 2.1.7 on 2019-04-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0024_auto_20190404_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='conselho',
            field=models.CharField(blank=True, choices=[('CREFITO', 'CREFITO'), ('CREF', 'CREF')], default='CREFITO', max_length=7, null=True, verbose_name='Conselho de Classe'),
        ),
    ]
