# Generated by Django 2.1.7 on 2019-03-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(default='Desempregado', max_length=50, verbose_name='Profissão'),
        ),
    ]
