# Generated by Django 2.1.7 on 2019-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefone1',
            field=models.CharField(default='99999-9999', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
    ]
