# Generated by Django 2.1.7 on 2019-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20190327_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hipertensao',
            field=models.BooleanField(default=False, verbose_name='Hipertensão'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profissao',
            field=models.CharField(default='Desempregado', max_length=200, verbose_name='Profissão'),
        ),
    ]
