# Generated by Django 2.1.7 on 2019-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20190710_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
