# Generated by Django 2.1.7 on 2019-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
