# Generated by Django 3.1 on 2020-08-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('duracao', models.TimeField(blank=True, null=True, verbose_name='Duração')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoPromocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_promocional', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor Promocional')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimentos.procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento em Promoção',
                'verbose_name_plural': 'Procedimentos em Promoções',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('termino', models.DateField(blank=True, null=True, verbose_name='Término')),
                ('procedimentos', models.ManyToManyField(blank=True, through='procedimentos.ProcedimentoPromocao', to='procedimentos.Procedimento')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='procedimentopromocao',
            name='promocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimentos.promocao'),
        ),
        migrations.AlterUniqueTogether(
            name='procedimentopromocao',
            unique_together={('promocao', 'procedimento')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='procedimentopromocao',
            order_with_respect_to='procedimento',
        ),
    ]
