# Generated by Django 3.1 on 2020-09-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='tipo_atendimento',
            field=models.SmallIntegerField(choices=[(0, 'ESTÉTICA'), (1, 'FISIOTERAPIA')], default=0, verbose_name='Tipo de Atendimento'),
        ),
    ]
