# Generated by Django 3.1 on 2020-08-28 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='profisioal',
            new_name='profissional',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(auto_now_add=datetime.time(20, 44, 51, 715019)),
        ),
    ]
