# Generated by Django 3.1 on 2020-08-30 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_auto_20200828_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(auto_now_add=datetime.time(15, 39, 19, 686584)),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('profissional', 'horario', 'data')},
        ),
    ]
