# Generated by Django 3.1 on 2020-08-30 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_auto_20200830_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(auto_now_add=datetime.time(21, 55, 13, 869141)),
        ),
    ]
