# Generated by Django 3.1 on 2020-09-01 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_auto_20200830_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(auto_now_add=datetime.time(13, 55, 48, 346162)),
        ),
    ]
