# Generated by Django 3.1 on 2020-09-17 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_auto_20200901_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentopago',
            name='total_pago',
        ),
        migrations.AlterField(
            model_name='agendamentopago',
            name='agendamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.agendamento'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(auto_now_add=datetime.time(18, 47, 38, 577923)),
        ),
    ]
