# Generated by Django 3.1 on 2020-09-18 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0006_auto_20200917_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Pago')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.agendamento')),
            ],
            options={
                'verbose_name': 'Registro de Pagamento do Agendamento',
                'verbose_name_plural': 'Registros de Pagamentos dos Agendamentos',
            },
        ),
        migrations.RemoveField(
            model_name='agendamentopago',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='agendamentopago',
            name='caixa',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(auto_now_add=datetime.time(18, 51, 19, 372330)),
        ),
        migrations.DeleteModel(
            name='AgendamentoFormasDePagamento',
        ),
        migrations.DeleteModel(
            name='AgendamentoPago',
        ),
        migrations.AddField(
            model_name='agendamentopagamento',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.caixa'),
        ),
        migrations.AddField(
            model_name='agendamentopagamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.formadepagamento'),
        ),
    ]
