# Generated by Django 3.1 on 2020-09-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0007_auto_20200918_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
