# Generated by Django 3.1 on 2020-09-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0008_auto_20200918_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='abertura',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateField(),
        ),
    ]
