# Generated by Django 3.1 on 2020-09-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0009_auto_20200918_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Desconto'),
        ),
    ]
