# Generated by Django 3.1 on 2020-09-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0010_agendamento_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentopagamento',
            name='horario',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
