# Generated by Django 3.1 on 2020-09-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0012_agendamento_valor_diferenciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('natureza', models.CharField(max_length=200)),
                ('tipo', models.SmallIntegerField(choices=[(0, 'ENTRADA'), (1, 'SAÍDA')], default=0)),
                ('horario', models.DateTimeField(verbose_name='Horário')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.caixa')),
                ('meio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.formadepagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.usuario')),
            ],
        ),
    ]
