# Generated by Django 3.1 on 2020-09-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0013_movimentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='meio',
            new_name='forma_pagamento',
        ),
    ]
