# Generated by Django 2.1.7 on 2019-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='procedimentos',
            field=models.ManyToManyField(through='clinica.PacoteProcedimento', to='clinica.Procedimento'),
        ),
    ]
