# Generated by Django 2.1.7 on 2019-03-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20190327_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoProntuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Procedimento')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Prontuario')),
            ],
            options={
                'verbose_name': 'Procedimento - Prontuario',
                'verbose_name_plural': 'Procedimentos - Prontuarios',
            },
        ),
    ]
