# Generated by Django 2.1.7 on 2019-03-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_procedimentoprontuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimentoprontuario',
            options={'verbose_name': 'Procedimento de Prontuario', 'verbose_name_plural': 'Procedimentos de Prontuarios'},
        ),
    ]
