# Generated by Django 2.1.7 on 2019-03-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0017_administrador'),
        ('clinica', '0007_auto_20190327_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data de Agendamento')),
                ('horario_agendamento', models.TimeField(verbose_name='Horário de Agendamento')),
                ('conduta', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'REALIZADA'), (0, 'CANCELADA'), (2, 'CONFIRMADA'), (3, 'À CONFIRMAR')], verbose_name='Situação')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Administrador')),
                ('procedimento_prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.ProcedimentoProntuario')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
            },
        ),
        migrations.CreateModel(
            name='SessaoEstetica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esteticista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Esteticista')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Sessao')),
            ],
            options={
                'verbose_name': 'Sessão de Estetica',
                'verbose_name_plural': 'Sessões de Estetica',
            },
        ),
        migrations.CreateModel(
            name='SessaoFisioterapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Fisioterapeuta')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Sessao')),
            ],
            options={
                'verbose_name': 'Sessão de Fisioterapia',
                'verbose_name_plural': 'Sessões de Fisioterapia',
            },
        ),
    ]
