# Generated by Django 2.1.7 on 2019-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_convenio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ATIVO'), (0, 'INATIVO')], default=1),
        ),
    ]
